### ISSUE TITLE
Error Compile

### ISSUE THREAD

**Issue by ashraful1980** [jimtje/walletlib#58]
Dear Sir,
I have run your program; it is found following error massage:
saad@saad-VirtualBox:~/Desktop/walletlib$ python3 -m dumpwallet wallet.dat -o output.txt
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saad/Desktop/walletlib/dumpwallet.py", line 4, in <module>
    wallet.parse(passphrase="abc")
  File "/home/saad/Desktop/walletlib/walletlib/walletdat.py", line 281, in parse
    dec = self.decrypter.decrypt(encrypted_privkey)
  File "/home/saad/Desktop/walletlib/walletlib/crypto.py", line 43, in decrypt
    return AES.new(self.chkey, AES.MODE_CBC, self.chiv).decrypt(data)[:32]
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/AES.py", line 232, in new
    return _create_cipher(sys.modules[__name__], key, mode, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/__init__.py", line 79, in _create_cipher
    return modes[mode](factory, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/_mode_cbc.py", line 274, in _create_cbc_cipher
    cipher_state = factory._create_base_cipher(kwargs)
  File "/usr/local/lib/python3.6/dist-packages/Crypto/Cipher/AES.py", line 92, in _create_base_cipher
    if len(key) not in key_size:
TypeError: object of type 'NoneType' has no len()

**Comment by jimtje** [comment]
Yes that means the passphrase you entered isn't correct. I should add some more instructive error messages to the script so that it is more clear

**Comment by ashraful1980** [comment]
Could you please set the option @ dictionary and character  for searching passphrase. It is helpful to find passphrase....

**Comment by jimtje** [comment]
It's pretty pointless to add in a brute force feature here, since having to load the db over and over again will make the process way too slow for it to be useful, and besides, if you're actually trying to crack the password, you really don't need to run that on the wallet file itself anyway. 

Grab [JohnTheRipper](https://github.com/openwall/john) and use the bitcoin2john.py file in the /run to extract the hash for the .dat file. Then, you can use whatever you want to run your lists or whatever. If you use hashcat, use -m 11300 for the hash. Johntheripper itself should be sufficient if you just want to run wordlists. You can also throw the hash at any site that takes it, like [OnlineHashCheck](https://www.onlinehashcrack.com/) or [Terahash](https://terahash.com/) or [GPUHash](https://gpuhash.me/). Pretty much in any scenario it's way quicker to attack the hash itself instead of the actual wallet, and also this allows you to outsource the process without the risk of also handing over your coins. Hope that helps.
